# ----------- CONFIGURABLE START -----------
title:            "蒋炳哲 blog"
description:      "欢迎来到 蒋炳哲「corner」梳理过去"
url:              https://codingjbz.github.io/E-Growth # 域名
signoff:          "蒋炳哲" # Your name
facebook_appid:   #liberxue
google_analytics: UA-112062722-2
share:            true 
# 分页
paginate: 15h
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
